'''
This tests the creation of state abstractions from the AbstractionMakers file based on the q-tables
generated by ValueIteration
'''

from MDP.ValueIterationClass import ValueIteration
from GridWorld.TaxiMDPClass import TaxiMDP
from GridWorld.GridWorldMDPClass import GridWorldMDP
from resources.AbstractionMakers import make_abstr
from resources.AbstractionMakers import Abstr_type

if __name__ == '__main__':
    # GridWorld tests
    mdp = GridWorldMDP(slip_prob=0.0, gamma=0.99)
    vi = ValueIteration(mdp)
    vi.doValueIteration()
    q_table = vi.get_q_table()
    for key in q_table.keys():
        print(key[0], key[1], q_table[key])
    abstr = make_abstr(q_table, Abstr_type.Q_STAR, epsilon=0.01)
    print(abstr)

