'''
This tests the creation of state abstractions from the AbstractionMakers file based on the q-tables
generated by ValueIteration
'''

from MDP.ValueIterationClass import ValueIteration
from GridWorld.TaxiMDPClass import TaxiMDP
from resources.AbstractionMakers import make_abstr
from resources.AbstractionMakers import Abstr_type

if __name__ == '__main__':
    # Create MDP,